---
title: "Example papaya viewer for Francisca"
author: "LC"
date: "2024-06-28"
output:
  html_document:
    self_contained: true
    code_folding: hide
    highlight: pygments
    theme: cerulean
    css: styles.css
---

# Load the libraries

```{r, message=FALSE}
library(shiny)
library(tidyverse)
library(papayaWidget)
library(RNifti)

preproc_data_dir="/data00/leonardo/GUTS_fmri_preproc/people/francisca/preproc_data_MNI"
```


# Retrieve info about files for all participants
```{r}
# List all files with T1w, mask, tsnr patterns
files <- list.files(
  preproc_data_dir,
  pattern = "sub-.*((desc-(preproc_T1w|brain_mask)|_tsnr|_isc)\\.nii\\.gz|_conf\\.svg)$",
  full.names = TRUE
)


# Extract sub_id and type from filenames
df <- tibble(file = files) %>%
  mutate(
    filename = basename(file),
    sub_id = str_extract(filename, "sub-[a-z0-9]+"),
    type = case_when(
      str_detect(filename, "desc-preproc_T1w") ~ "T1w",
      str_detect(filename, "desc-brain_mask") ~ "mask",
      str_detect(filename, "_tsnr") ~ "tsnr",
      str_detect(filename, "_isc") ~ "isc",
      str_detect(filename, "\\.svg$") ~ "svg",       # <-- added this line
      TRUE ~ NA_character_
    )
  ) %>%
  filter(!is.na(type)) %>%
  select(sub_id, type, file) %>%
  pivot_wider(names_from = type, values_from = file)


```

```{r}
sub="sub-gutslei0126"

files <- df[df$sub_id == sub, c("T1w", "isc")]
imgs <- na.omit(as.character(unlist(files)))

papaya(
  imgs,
  # sync_view = TRUE,
  hide_controls = TRUE,
  option = list(
    papayaOptions(lut = "Grayscale"),
    papayaOptions(lut = "Red Overlay", alpha = 0.5, min = 0.4, max = 1)
  ),
  interpolation = FALSE,
  title = "Brain_mask"
)


do_papaya <- function(sub, imgs_vector) {
  
  files <- df[df$sub_id == sub, imgs_vector]
  imgs <- na.omit(as.character(unlist(files)))
  
  w <- papaya(
    imgs,
    # sync_view = TRUE,
    hide_controls = TRUE,
    option = list(
      papayaOptions(lut = "Grayscale"),
      papayaOptions(lut = "Red Overlay", alpha = 0.5, min = 0.4, max = 1)
    ),
    interpolation = FALSE,
    title = "Brain_mask"
  )
  
  return(w)
}


```


```{r}
papaya_viewer_1 = do_papaya(sub="sub-gutslei0126", imgs_vector=c("T1w", "isc")) 
papaya_viewer_1
```



```{r}
papaya_viewer_2 = do_papaya(sub="sub-gutslei0126", imgs_vector=c("T1w", "mask")) 
papaya_viewer_2
```








